services:
  frontend:
    image: lorena285/astrozone-frontend:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=astrozone.lorainecode.cl
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=astrozone.lorainecode.cl
      - LETSENCRYPT_EMAIL=gonzalezm.lorena2@gmail.com
    depends_on:
      - backend
    networks:
      - proxy

  backend:
    image: lorena285/astrozone-backend:latest
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=api.astrozone.lorainecode.cl
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.astrozone.lorainecode.cl
      - LETSENCRYPT_EMAIL=gonzalezm.lorena2@gmail.com
      - ALLOWED_ORIGINS=http://astrozone.lorainecode.cl,https://astrozone.lorainecode.cl
    networks:
      - proxy

networks:
  proxy:
    external: true
